package ar.edu.unlam.pb1;

public enum MenuPrincipal {

	AGREGAR_PROPIEDADES, MODIFICAR_PROPIEDADES, AGREGAR_CLIENTE, 
	OBTENER_PROPIEDADES_ORDENADAS_POR_PRECIO,
	OBTENER_PROPIEDADES_ORDENADAS_POR_UBICACION, 
	BUSCAR_PROPIEDADES_POR_PRECIO, BUSCAR_PROPIEDADES_POR_UBICACION,
	REALIZAR_VENTA, REALIZAR_ALQUILER,SALIR
}
